### ISSUE TITLE
Update API for DATA_OBJ_READ_AN to 4.X

### ISSUE THREAD

**Issue by PhillipsOwen** [DICE-UNC/irods-php#15]
AN DATA_OBJ_READ_AN causes an error in iRODS 4.x. 

DATA_OBJ_READ_AN needs to be updated to new API.

In: https://github.com/DICE-UNC/irods-php/blob/master/prods/src/RODSConn.class.php#L983-L995

Thanks!

**Comment by trel** [comment]
Please mark this as bug @michael-conway 

I can't edit issues in this repo - thanks.

**Comment by michael-conway** [comment]
Currently the api looks correct, writing up a PHP Unit for this and cruft to support it.  The current test is just a dumb stub.
